apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-service
spec:
  template:
    spec:
      containers:
        - name: pet-service
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: AWS_REGION
              value: "us-west-2"
          image: 304930966996.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-pet-service:57d5d403fa274b9aea1e841bc428f132c67fc464
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-service
spec:
  template:
    spec:
      containers:
        - name: hospital-service
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: AWS_REGION
              value: "us-west-2"
          image: 304930966996.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-hospital-service:57d5d403fa274b9aea1e841bc428f132c67fc464
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
spec:
  template:
    spec:
      containers:
        - name: doctor-service
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: AWS_REGION
              value: "us-west-2"
          image: 304930966996.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-doctor-service:57d5d403fa274b9aea1e841bc428f132c67fc464
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: API_URL
              value: "http://frontend-ingress"
          image: 304930966996.dkr.ecr.us-west-2.amazonaws.com/pet-hospital-frontend:57d5d403fa274b9aea1e841bc428f132c67fc464
