apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pet-service.yaml
  - hospital-service.yaml
  - doctor-service.yaml
  - frontend.yaml
  - frontend-ingress.yaml

namespace: pethospital-dev
